### ISSUE TITLE
404 in Mode-Line-Data.html

### ISSUE THREAD

**Issue by kosh04** [ayatakesi/emacs-24.5-doc-lispref#1]
問題のページ: https://ayatakesi.github.io/lispref/24.5/elisp_html/Mode-Line-Data.html
リンクテキスト: %-Constructs
リンク先(404): https://ayatakesi.github.io/lispref/24.5/elisp_html/_0025_002dConstructs.html#g_t_0025_002dConstructs

一応、報告しておきます。

**Comment by ayatakesi** [comment]
確認します、ありがとうございます。

**Comment by ayatakesi** [comment]
バグ報告しました。
http://debbugs.gnu.org/cgi/bugreport.cgi?bug=37508
遅くなり申し訳ありませんです

**Comment by ayatakesi** [comment]
%という特殊文字(っぽいの)が含まれてたんで、てっきり上流のtypoだと早とちりしてしまいました。もう一回調べます

**Comment by ayatakesi** [comment]
github pagesのknown issueとのことです
https://help.github.com/en/articles/files-that-start-with-an-underscore-are-missing
ので、ayatakesi/ayatakesi.github.io#1 にissue開きました
